Assign :Token name,Expr value
PlusAssign :Token name,Expr value
MinusAssign :Token name,Expr value
StarAssign :Token name,Expr value
SlashAssign :Token name,Expr value
Binary:Expr left,Token operator,Expr right
Call:Expr callee,Token paren,Expr[] args
Grouping :Expr expression
LambdaFunction: Token[] params,Stmt[] body
Literal :Object|null value
Template:Expr[] blocks
Logical: Expr left,Token operator,Expr right
Unary :Token operator,Expr right
Variable :Token name