Assign :Token name,Expr value
PlusAssign :Token name,Expr value
MinusAssign :Token name,Expr value
StarAssign :Token name,Expr value
SlashAssign :Token name,Expr value
Binary:Expr left,Token operator,Expr right
Call:Expr callee,Token paren,Expr[] arguments
Grouping :Expr expression
Literal :Object|null value
Logical: Expr left,Token operator,Expr right
Unary :Token operator,Expr right
Variable :Token name