Assign :Token name,Expr value
Binary:Expr left,Token operator,Expr right
Call:Expr callee,Token paren,Expr[] args
Grouping :Expr expression
LambdaFunction: Token[] params,Stmt[] body
Literal :Object|null value
Template:Expr[] blocks
Logical: Expr left,Token operator,Expr right
Unary :Token operator,Expr right
Array:Expr[] elements
ArrayCall: Token paren,Expr expr_paren,Expr index
Variable :Token name